# FMT System Configuration File

# The target should match with BSP's target name
target = "Pixhawk FMUv2"

# Console Configuration
[console]
	# device list, the first device will be used by default
	[[console.devices]]
	type = "serial"         	# type must be serial or mavlink
	name = "serial0"        	# device name
	baudrate = 57600        	# serial baudrate
	auto-switch = true      	# automatically switch to device if data received
	
	[[console.devices]]
	type = "mavlink"        	# type must be serial or mavlink
	name = "mav_console"    	# device name
	auto-switch = true      	# automatically switch to device if data received

# Pilot CMD Configuration
[pilot-cmd]
	stick-channel = [4,3,1,2]	# channel mapping for [ls_lr,ls_ud,rs_lr,rs_ud]
	
	[pilot-cmd.device]
	type = "rc"					# type must be rc
	name = "rc"             	# device name
	protocol = 2            	# 1:sbus, 2:ppm
	channel-num = 6         	# channel in used, max supported channel: sbus:16, ppm:8
	sample-time = 0.05      	# sample time in second (-1 for inherit)
	range = [1000,2000]     	# min and max value
	
	[[pilot-cmd.mode]]
	mode = 2                	# position mode
	channel = 5             	# mode channel
	range = [1000,1200]     	# if channel value in this range, the mode is selected
	
	[[pilot-cmd.mode]]
	mode = 3                	# altitude hold mode
	channel = 5
	range = [1400,1600]
	
	[[pilot-cmd.mode]]
	mode = 4                	# manual mode
	channel = 5
	range = [1800,2000]
	
	[[pilot-cmd.command]]
	type = 1                	# 1:event | 2:status
	cmd = 1000              	# force-disarm: forcely disarm motors for safety concern
	channel = 6             	# command channel
	range = [1800,2000]     	# if channel value in this range, the event is triggered
	
# Mavproxy Device Configuration
[mavproxy]
	[[mavproxy.devices]]		# channel 0
	type = "serial"
	name = "serial1"        	# device name
	baudrate = 57600        	# serial baudrate
	
	[[mavproxy.devices]]		# channel 1
	type = "usb"
	name = "usb"				# device name
	# automatically switch to usb if connected, switch back to default device is disconnected
	auto-switch = true

# Actuator Command Configuration
[actuator-cmd]
    [actuator-cmd.device]
    type = "pwm"                # type must be pwm now
    name = "motor_main"         # device name
    freq = 400                  # pwm frequency in Hz
    chan-idx = 0x000F           # map control output 1-4 to main out
    range = [1000,2000]         # control output range